name: Greeting2
on: [push, workflow_dispatch]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4   # ✅ add 'v'

      - name: Install node
        uses: actions/setup-node@v4  # ✅ add 'v'
        with:
          node-version: 20

      - name: Print node version
        run: node -v

      - name: Cache file
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm run test
  Build:
    needs: Test
    runs-on: Ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4   # ✅ add 'v'

      - name: Install node
        uses: actions/setup-node@v4  # ✅ add 'v'
        with:
          node-version: 20

      - name: Print node version
        run: node -v

      - name: Cache file
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
            name: dist-files
            path: dist

  deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
            name: dist-files
            path: dist

      - name: Deploy
        run: echo "Successfully deploied"